# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:

  # build job runs for all branches and all tags.
  build:
    docker:
      # Specify the version you desire here
      # https://circleci.com/docs/2.0/circleci-images/#nodejs
      - image: circleci/node:lts

    # set working directory to sub folder
    working_directory: ~/repo/middleware

    steps:
      - checkout:
          path: ~/repo

      - run:  # Access to @heroku/salesforce-sdk
          name: Middleware Build and Test Prep
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run: npm install
      - run: npm run build
      - run: npm run test
      - run: echo "jq is installed on " $(which jq)
      - run: cd .. && make package && ls -alh sf-fx-middleware-buildpack-*.tgz
      - run: VERSION_TOML=v$(cat buildpack.toml | grep -m 1 version | sed -e 's/version = //g' | xargs)
      - run: echo ${VERSION_TOML}

      - persist_to_workspace:
          root: ~/repo
          paths:
            - sf-fx-middleware-buildpack-*.tgz
            - buildpack.toml
            - ci-git-release.sh

  #release job runs for no branches and only for tags starting with ‘v’.        
  release: 
    docker:
      - image: cibuilds/github:0.13.0
          # set working directory to sub folder
    working_directory: ~/repo

    steps:
      - run: echo "ghr is installed on " $(which ghr)
      - run: echo "run github command to upload the binary on " ${CIRCLE_BRANCH}:${CIRCLE_TAG}
      - attach_workspace:
          at: ~/repo
      - run: ls -alh
      - run: echo "jq is installed on " $(which jq)
      - run: ./ci-git-release.sh

workflows:
  version: 2
  build-and-release:
    jobs:
      - build
      - release:
          requires:
            - build
  
