# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # Specify the version you desire here
      # https://circleci.com/docs/2.0/circleci-images/#nodejs
      - image: circleci/node:lts

    working_directory: ~/repo

    steps:
      - checkout

    # Access to @heroku/salesforce-sdk
      - run:
          name: Middleware Build and Test Prep
          command: cd middleware && echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc

      - run: cd middleware && npm install

      - run: cd middleware && npm run build

      - run: cd middleware && npm run test